// nuxt-app/components/ExploreContainer.vue
<script setup lang="ts">
defineProps({ name: String })
</script>

<template>
  <div id="container">
    <strong>{{ name }}</strong>
    <p>Explore <a target="_blank" rel="noopener noreferrer" href="https://ionicframework.com/docs/components">UI Components</a></p>
  </div>
</template>

<style scoped>
#container {
  text-align: center;
  position: absolute;
  left: 0;
  right: 0;
  top: 50%;
  transform: translateY(-50%);
}

#container strong {
  font-size: 20px;
  line-height: 26px;
}

#container p {
  font-size: 16px;
  line-height: 22px;
  color: #8c8c8c;
  margin: 0;
}

#container a {
  text-decoration: none;
}
</style>

// next-app/components/ExploreContainer.tsx
import styles from '../styles/ExploreContainer.module.css';

interface ContainerProps {
  name: string;
}

const ExploreContainer: React.FC<ContainerProps> = ({ name }) => {
  return (
    <div className={styles.container}>
      <strong>{name}</strong>
      <p>
        Explore{' '}
        <a
          target='_blank'
          rel='noopener noreferrer'
          href='https://ionicframework.com/docs/components'
        >
          UI Components
        </a>
      </p>
    </div>
  );
};

export default ExploreContainer;
